version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: udyam
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./udyam-backend
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/udyam
    depends_on:
      - db
    volumes:
      - ./udyam-backend:/app
    command: npm run dev

volumes:
  pgdata:
